name: build on windows

on:
  push:
    branches: [develop]
  pull_request:
    types: [develop]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: ilammy/msvc-dev-cmd@v1

      - name: buildmain
        run: |
          sys/winnt/nhsetup
          cd src
          nmake install

      - name: archive
        run: |
          7z a latest.zip binary/

      - name: tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action/tree/main
        with:
          name: "latest"
          allowUpdates: true
          tag: latest
          commit: jnh
          replacesArtifacts: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ./latest.zip
